/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPostForm: typeof import('./src/components/UserDetail/UserPosts/AddPostForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    UserDetailCard: typeof import('./src/components/UserDetail/UserDetailCard/UserDetailCard.vue')['default']
    UserDetailCardSkeleton: typeof import('./src/components/UserDetail/UserDetailCard/UserDetailCardSkeleton.vue')['default']
    UserList: typeof import('./src/components/Users/UserList.vue')['default']
    UserPostList: typeof import('./src/components/UserDetail/UserPosts/UserPostList.vue')['default']
    UserPostListSkeleton: typeof import('./src/components/UserDetail/UserPosts/UserPostListSkeleton.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
